version: '3'

services:
    db:
        image: postgres
        ports:
            - "5432:5432"
        container_name: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ~/postgres/data:/var/lib/postgresql/data

    
    fetch:
        image: ramailh/fetch-movie-data
        ports:
            - "9080:9080"
        container_name: fetch-movie-data
        restart: always
        env_file: 
            - fetch.env

    logger:
        image: ramailh/logger
        ports:
            - "57600"
        container_name: logger
        restart: always
        env_file: 
            - logger.env
